/**
 * Client-side copy. Vietnamese only, full diacritics, never inline in TSX —
 * Biome's noJsxLiterals enforces the rule for bare text; string props are on
 * you. Namespaced per screen/concept, never merged on coincidental wording.
 *
 * Interpolation convention (decided here so Phase 1's ~54 pages don't each
 * improvise one): a template holds `{param}` placeholders —
 * `overdueCount: "Có {count} sách quá hạn"` — and callers pass values through
 * `t()` below: `t(copy.manage.overdueCount, { count: 3 })`. Every
 * placeholder must be supplied; a template is never partially interpolated
 * with string concatenation, and a count/date/name is never spliced into a
 * copy string any other way.
 */
export const copy = {
    common: {
        appName: "OLibra",
        signIn: "Đăng nhập",
        signOut: "Đăng xuất",
        underConstruction: "Trang này đang được xây dựng.",
        backHome: "Về trang chủ",
    },
    home: {
        title: "Tủ sách giáo xứ",
        lead: "Mượn sách, trả sách và cùng đọc với cộng đoàn.",
        browseShelves: "Xem các tủ sách",
    },
    shelves: {
        title: "Các tủ sách",
        empty: "Chưa có tủ sách nào.",
    },
    shelf: {
        catalogue: "Danh mục",
        search: "Tìm kiếm",
        announcements: "Thông báo",
        profile: "Hồ sơ",
        manage: "Quản lý",
    },
    manage: {
        dashboard: "Tổng quan",
        lend: "Cho mượn",
        returns: "Nhận trả",
        readers: "Người đọc",
        books: "Sách",
        settings: "Cài đặt",
    },
    admin: {
        title: "Quản trị hệ thống",
        shelves: "Tủ sách",
        managers: "Người quản lý",
        categories: "Thể loại",
        settings: "Cài đặt",
    },
    auth: {
        title: "Đăng nhập",
        username: "Tên đăng nhập",
        password: "Mật khẩu",
        submit: "Đăng nhập",
    },
    catalogue: {
        title: "Danh mục sách",
        searchTitle: "Tìm kiếm",
        searchPlaceholder: "Tìm theo tên sách hoặc tác giả…",
        scopeAvailable: "Sách có sẵn",
        scopeAll: "Tất cả",
        sortRecent: "Mới thêm",
        sortTitle: "Tên sách",
        allCategories: "Mọi thể loại",
        emptyList: "Không có sách nào khớp với bộ lọc.",
        emptySearch: "Không tìm thấy sách nào.",
        totalCount: "{count} đầu sách",
        pagePrev: "Trang trước",
        pageNext: "Trang sau",
        pageOf: "Trang {page}/{pageCount}",
        copyCountLine: "{available} bản có sẵn · {onLoan} đang cho mượn · {total} bản trong tủ",
        queueLine: "{count} người đang chờ mượn",
        holderLine: "{name} đang mượn, còn {days} ngày",
        holderLineAnonymous: "Đang có người mượn, còn {days} ngày",
        holderLineOverdue: "{name} đang mượn, quá hạn {days} ngày",
        contactBefore: "Liên hệ {name} · ",
        contactAfter: " để nhận sách",
        author: "Tác giả",
        publisher: "Nhà xuất bản",
        publishedYear: "Năm xuất bản",
        pageCount: "Số trang",
        category: "Thể loại",
        isbn: "Mã ISBN",
        description: "Giới thiệu",
        state: {
            available: "Có sẵn",
            on_loan: "Đang cho mượn",
            held: "Đang giữ chỗ",
            lost: "Đã mất",
            retired: "Ngừng dùng",
            none: "Chưa có bản nào",
        },
        condition: {
            perfect: "Nguyên vẹn",
            slightly_worn: "Hơi cũ",
            worn: "Cũ",
            torn: "Rách",
            missing_pages: "Mất trang",
            written_on: "Bị vẽ vào",
        },
    },
    readerCatalogue: {
        borrowSoon: "Chức năng xin mượn sẽ có trong giai đoạn sau.",
        availableWithCount: "Còn {count} bản có sẵn",
        searchLead: 'Gõ không dấu cũng tìm được — thử "tim kiem kho bau".',
        searchEmptyPrompt: "Nhập từ khoá để tìm sách.",
        suggestionsHeading: "Sách mới thêm gần đây",
    },
    manageBooks: {
        title: "Sách",
        addBook: "Thêm sách mới",
        editBook: "Sửa sách",
        viewCopies: "Xem bản",
        lostChip: "Đã mất ({count})",
        draftBadge: "Bản nháp",
        fields: {
            title: "Tên sách",
            author: "Tác giả",
            category: "Thể loại",
            categoryEmpty: "— chọn thể loại —",
            publisher: "Nhà xuất bản",
            publishedYear: "Năm xuất bản",
            pageCount: "Số trang",
            isbn: "Mã ISBN",
            description: "Giới thiệu",
            copyCount: "Số bản sách",
            donorName: "Người tặng (nếu có)",
            acquiredOn: "Ngày nhận",
            isPublished: "Hiện sách này cho bạn đọc",
        },
        save: "Lưu",
        saving: "Đang lưu…",
        copiesHeading: "Các bản sách",
        addCopies: "Thêm bản",
        addCopiesCount: "Số bản thêm",
        copyCode: "Mã",
        copyState: "Trạng thái",
        copyCondition: "Tình trạng",
        copyWhere: "Đang ở đâu",
        onShelf: "Trên kệ",
        withReader: "{name} mượn, hẹn trả {date}",
        overdueBadge: "Quá hạn",
        donorColumn: "Người tặng",
        assess: "Đánh giá",
        assessNote: "Ghi chú",
        reportLost: "Báo mất",
        markFound: "Đánh dấu tìm thấy",
        retire: "Ngừng dùng",
        retireReason: "Lý do ngừng dùng",
        retiredWithReason: "Ngừng dùng: {reason}",
        confirm: "Xác nhận",
        cancel: "Huỷ",
        conditionHistory: "Lịch sử đánh giá",
        loanHistory: "Lịch sử mượn trả",
        historyEmpty: "Chưa có dữ liệu.",
        lostTitle: "Sách đã mất",
        lostEmpty: "Không có bản sách nào đang bị báo mất.",
        lostReportedAt: "Báo mất lúc {date}",
        lostLastBorrower: "Người mượn gần nhất: {name}",
        backToList: "Về danh sách sách",
    },
    register: {
        title: "Đăng ký làm bạn đọc",
        lead: "Điền giúp mình vài thông tin. Quản lý tủ sách sẽ gặp và duyệt tài khoản sau lễ Chúa nhật.",
        chooseFirst: "Trước hết, bạn chọn tủ sách của giáo xứ mình nhé.",
        chooseShelf: "Xem danh sách tủ sách",
        forShelf: "Đăng ký cho tủ sách",
        changeShelf: "Chọn tủ sách khác",
        sent: "Đã gửi đăng ký. Quản lý sẽ gặp bạn ở nhà xứ để xác nhận.",
        groupCredentials: "Đăng nhập",
        credentialsNote:
            "Để trống cũng được — bạn chỉ cần tên đăng nhập nếu muốn tự xem sách ở nhà. Quản lý có thể tạo sau.",
        username: "Tên đăng nhập",
        usernameHint: "Dùng để đăng nhập, nên chọn tên dễ nhớ.",
        password: "Mật khẩu",
        passwordHint: "Ít nhất 8 ký tự. Nếu quên, quản lý sẽ đặt lại giúp.",
        passwordConfirm: "Nhập lại mật khẩu",
        groupPerson: "Bản thân",
        saintName: "Tên thánh",
        saintNameHint: "Theo sổ giáo xứ, để quản lý dễ nhận ra bạn.",
        fullName: "Họ và tên",
        fullNameHint: "Ghi đầy đủ như trong sổ giáo xứ.",
        dateOfBirth: "Ngày sinh",
        dateOfBirthHint: "Để tủ sách gợi ý sách hợp tuổi.",
        groupFamily: "Gia đình",
        fatherName: "Tên cha",
        motherName: "Tên mẹ",
        parentHint: "Giúp quản lý phân biệt các bạn đọc trùng tên.",
        phone: "Số điện thoại liên hệ",
        phoneHint: "Số của cha mẹ cũng được. Để trống thì cần cho biết lý do bên dưới.",
        phoneMissingReason: "Lý do chưa có số điện thoại",
        phoneMissingHint: "Ví dụ: em bé chưa có điện thoại riêng, sẽ bổ sung sau.",
        phoneDialogTitle: "Chưa có số điện thoại?",
        phoneDialogBody:
            "Số điện thoại là cách quản lý liên hệ khi sách đến hạn. Nếu chưa có, bạn cho biết lý do nhé.",
        phoneDialogConfirm: "Gửi với lý do này",
        phoneDialogCancel: "Quay lại nhập số",
        groupParish: "Giáo xứ",
        parishNote:
            "Không bắt buộc. Chưa biết cũng cứ gửi đăng ký — quản lý bổ sung giúp sau khi gặp bạn.",
        noUnit: "— Không chọn —",
        afterTitle: "Sau khi gửi thì sao?",
        afterBody:
            "Tài khoản chưa dùng được ngay. Quản lý sẽ gặp bạn ở nhà xứ để xác nhận, thường trong vòng một tuần.",
        submit: "Gửi đăng ký",
        haveAccount: "Đã có tài khoản? Đăng nhập",
        required: "Bắt buộc",
    },
    membershipStatus: {
        pending: "Chờ duyệt",
        active: "Đang hoạt động",
        suspended: "Tạm khoá",
        left: "Đã rời",
        rejected: "Đã từ chối",
    },
    manageReaders: {
        title: "Người đọc",
        addReader: "Đăng ký người đọc mới",
        searchPlaceholder: "Tìm theo tên…",
        search: "Tìm",
        statusAll: "Tất cả",
        unitAll: "Mọi đơn vị",
        holding: "Đang mượn {count}",
        totalCount: "{count} bạn đọc",
        empty: "Chưa có bạn đọc nào khớp bộ lọc.",
        pagePrev: "Trang trước",
        pageNext: "Trang sau",
        pageOf: "Trang {page}/{pageCount}",
        createTitle: "Đăng ký người đọc mới",
        createLead:
            "Điền thay cho bạn đọc đang đứng trước mặt. Hồ sơ vẫn chờ duyệt để bước xác nhận không bị bỏ qua.",
        createSubmit: "Tạo hồ sơ chờ duyệt",
    },
    registrationQueue: {
        title: "Đăng ký chờ duyệt",
        empty: "Không có đơn đăng ký nào đang chờ.",
        requestedAt: "Gửi lúc {time}",
        dateOfBirth: "Ngày sinh",
        father: "Tên cha",
        mother: "Tên mẹ",
        phone: "Số điện thoại",
        phoneMissing: "Chưa có số — lý do: {reason}",
        parish: "Đơn vị",
        similar: "Gần trùng tên với {name} ({percent}%) — kiểm tra xem có phải đăng ký hai lần.",
        approve: "Duyệt đăng ký",
        reject: "Từ chối",
        rejectReason: "Lý do từ chối",
    },
} as const;

/**
 * Fill a copy template's `{param}` placeholders. A missing param leaves the
 * placeholder text visible (`{count}`) rather than silently rendering
 * "undefined" — a wrong caller shows up as an obviously broken string
 * instead of a plausible one.
 */
export function t(template: string, params: Record<string, string | number>): string {
    return template.replace(/\{(\w+)\}/g, (match, key: string) =>
        key in params ? String(params[key]) : match,
    );
}
