/**
 * Client-side copy. Vietnamese only, full diacritics, never inline in TSX —
 * Biome's noJsxLiterals enforces the rule for bare text; string props are on
 * you. Namespaced per screen/concept, never merged on coincidental wording.
 *
 * Interpolation convention (decided here so Phase 1's ~54 pages don't each
 * improvise one): a template holds `{param}` placeholders —
 * `overdueCount: "Có {count} sách quá hạn"` — and callers pass values through
 * `t()` below: `t(copy.manage.overdueCount, { count: 3 })`. Every
 * placeholder must be supplied; a template is never partially interpolated
 * with string concatenation, and a count/date/name is never spliced into a
 * copy string any other way.
 */
export const copy = {
    common: {
        appName: "OLibra",
        signIn: "Đăng nhập",
        signOut: "Đăng xuất",
        underConstruction: "Trang này đang được xây dựng.",
        backHome: "Về trang chủ",
    },
    home: {
        title: "Tủ sách giáo xứ",
        lead: "Mượn sách, trả sách và cùng đọc với cộng đoàn.",
        browseShelves: "Xem các tủ sách",
    },
    shelves: {
        title: "Các tủ sách",
        empty: "Chưa có tủ sách nào.",
    },
    shelf: {
        catalogue: "Danh mục",
        search: "Tìm kiếm",
        announcements: "Thông báo",
        profile: "Hồ sơ",
        manage: "Quản lý",
    },
    manage: {
        dashboard: "Tổng quan",
        lend: "Cho mượn",
        returns: "Nhận trả",
        readers: "Người đọc",
        books: "Sách",
        overdue: "Quá hạn",
        requests: "Yêu cầu mượn",
        settings: "Cài đặt",
        audit: "Nhật ký",
    },
    admin: {
        title: "Quản trị hệ thống",
        shelves: "Tủ sách",
        managers: "Người quản lý",
        categories: "Thể loại",
        settings: "Cài đặt",
    },
    auth: {
        title: "Đăng nhập",
        username: "Tên đăng nhập",
        password: "Mật khẩu",
        submit: "Đăng nhập",
    },
    catalogue: {
        title: "Danh mục sách",
        searchTitle: "Tìm kiếm",
        searchPlaceholder: "Tìm theo tên sách hoặc tác giả…",
        scopeAvailable: "Sách có sẵn",
        scopeAll: "Tất cả",
        sortRecent: "Mới thêm",
        sortTitle: "Tên sách",
        allCategories: "Mọi thể loại",
        emptyList: "Không có sách nào khớp với bộ lọc.",
        emptySearch: "Không tìm thấy sách nào.",
        totalCount: "{count} đầu sách",
        pagePrev: "Trang trước",
        pageNext: "Trang sau",
        pageOf: "Trang {page}/{pageCount}",
        copyCountLine: "{available} bản có sẵn · {onLoan} đang cho mượn · {total} bản trong tủ",
        queueLine: "{count} người đang chờ mượn",
        holderLine: "{name} đang mượn, còn {days} ngày",
        holderLineAnonymous: "Đang có người mượn, còn {days} ngày",
        holderLineOverdue: "{name} đang mượn, quá hạn {days} ngày",
        contactBefore: "Liên hệ {name} · ",
        contactAfter: " để nhận sách",
        author: "Tác giả",
        publisher: "Nhà xuất bản",
        publishedYear: "Năm xuất bản",
        pageCount: "Số trang",
        category: "Thể loại",
        isbn: "Mã ISBN",
        description: "Giới thiệu",
        state: {
            available: "Có sẵn",
            on_loan: "Đang cho mượn",
            held: "Đang giữ chỗ",
            lost: "Đã mất",
            retired: "Ngừng dùng",
            none: "Chưa có bản nào",
        },
        condition: {
            perfect: "Nguyên vẹn",
            slightly_worn: "Hơi cũ",
            worn: "Cũ",
            torn: "Rách",
            missing_pages: "Mất trang",
            written_on: "Bị vẽ vào",
        },
    },
    readerCatalogue: {
        borrowSoon: "Chức năng xin mượn sẽ có trong giai đoạn sau.",
        availableWithCount: "Còn {count} bản có sẵn",
        searchLead: 'Gõ không dấu cũng tìm được — thử "tim kiem kho bau".',
        searchEmptyPrompt: "Nhập từ khoá để tìm sách.",
        suggestionsHeading: "Sách mới thêm gần đây",
    },
    manageBooks: {
        title: "Sách",
        addBook: "Thêm sách mới",
        editBook: "Sửa sách",
        viewCopies: "Xem bản",
        lostChip: "Đã mất ({count})",
        draftBadge: "Bản nháp",
        fields: {
            title: "Tên sách",
            author: "Tác giả",
            category: "Thể loại",
            categoryEmpty: "— chọn thể loại —",
            publisher: "Nhà xuất bản",
            publishedYear: "Năm xuất bản",
            pageCount: "Số trang",
            isbn: "Mã ISBN",
            description: "Giới thiệu",
            copyCount: "Số bản sách",
            donorName: "Người tặng (nếu có)",
            acquiredOn: "Ngày nhận",
            isPublished: "Hiện sách này cho bạn đọc",
        },
        save: "Lưu",
        saving: "Đang lưu…",
        copiesHeading: "Các bản sách",
        addCopies: "Thêm bản",
        addCopiesCount: "Số bản thêm",
        copyCode: "Mã",
        copyState: "Trạng thái",
        copyCondition: "Tình trạng",
        copyWhere: "Đang ở đâu",
        onShelf: "Trên kệ",
        withReader: "{name} mượn, hẹn trả {date}",
        overdueBadge: "Quá hạn",
        donorColumn: "Người tặng",
        assess: "Đánh giá",
        assessNote: "Ghi chú",
        reportLost: "Báo mất",
        markFound: "Đánh dấu tìm thấy",
        retire: "Ngừng dùng",
        retireReason: "Lý do ngừng dùng",
        retiredWithReason: "Ngừng dùng: {reason}",
        confirm: "Xác nhận",
        cancel: "Huỷ",
        conditionHistory: "Lịch sử đánh giá",
        loanHistory: "Lịch sử mượn trả",
        historyEmpty: "Chưa có dữ liệu.",
        lostTitle: "Sách đã mất",
        lostEmpty: "Không có bản sách nào đang bị báo mất.",
        lostReportedAt: "Báo mất lúc {date}",
        lostLastBorrower: "Người mượn gần nhất: {name}",
        backToList: "Về danh sách sách",
    },
    register: {
        title: "Đăng ký làm bạn đọc",
        lead: "Điền giúp mình vài thông tin. Quản lý tủ sách sẽ gặp và duyệt tài khoản sau lễ Chúa nhật.",
        chooseFirst: "Trước hết, bạn chọn tủ sách của giáo xứ mình nhé.",
        chooseShelf: "Xem danh sách tủ sách",
        forShelf: "Đăng ký cho tủ sách",
        changeShelf: "Chọn tủ sách khác",
        sent: "Đã gửi đăng ký. Quản lý sẽ gặp bạn ở nhà xứ để xác nhận.",
        groupCredentials: "Đăng nhập",
        credentialsNote:
            "Để trống cũng được — bạn chỉ cần tên đăng nhập nếu muốn tự xem sách ở nhà. Quản lý có thể tạo sau.",
        username: "Tên đăng nhập",
        usernameHint: "Dùng để đăng nhập, nên chọn tên dễ nhớ.",
        password: "Mật khẩu",
        passwordHint: "Ít nhất 8 ký tự. Nếu quên, quản lý sẽ đặt lại giúp.",
        passwordConfirm: "Nhập lại mật khẩu",
        groupPerson: "Bản thân",
        saintName: "Tên thánh",
        saintNameHint: "Theo sổ giáo xứ, để quản lý dễ nhận ra bạn.",
        fullName: "Họ và tên",
        fullNameHint: "Ghi đầy đủ như trong sổ giáo xứ.",
        dateOfBirth: "Ngày sinh",
        dateOfBirthHint: "Để tủ sách gợi ý sách hợp tuổi.",
        groupFamily: "Gia đình",
        fatherName: "Tên cha",
        motherName: "Tên mẹ",
        parentHint: "Giúp quản lý phân biệt các bạn đọc trùng tên.",
        phone: "Số điện thoại liên hệ",
        phoneHint: "Số của cha mẹ cũng được. Để trống thì cần cho biết lý do bên dưới.",
        phoneMissingReason: "Lý do chưa có số điện thoại",
        phoneMissingHint: "Ví dụ: em bé chưa có điện thoại riêng, sẽ bổ sung sau.",
        phoneDialogTitle: "Chưa có số điện thoại?",
        phoneDialogBody:
            "Số điện thoại là cách quản lý liên hệ khi sách đến hạn. Nếu chưa có, bạn cho biết lý do nhé.",
        phoneDialogConfirm: "Gửi với lý do này",
        phoneDialogCancel: "Quay lại nhập số",
        groupParish: "Giáo xứ",
        parishNote:
            "Không bắt buộc. Chưa biết cũng cứ gửi đăng ký — quản lý bổ sung giúp sau khi gặp bạn.",
        noUnit: "— Không chọn —",
        afterTitle: "Sau khi gửi thì sao?",
        afterBody:
            "Tài khoản chưa dùng được ngay. Quản lý sẽ gặp bạn ở nhà xứ để xác nhận, thường trong vòng một tuần.",
        submit: "Gửi đăng ký",
        haveAccount: "Đã có tài khoản? Đăng nhập",
        required: "Bắt buộc",
    },
    membershipStatus: {
        pending: "Chờ duyệt",
        active: "Đang hoạt động",
        suspended: "Tạm khoá",
        left: "Đã rời",
        rejected: "Đã từ chối",
    },
    manageReaders: {
        title: "Người đọc",
        addReader: "Đăng ký người đọc mới",
        searchPlaceholder: "Tìm theo tên…",
        search: "Tìm",
        statusAll: "Tất cả",
        unitAll: "Mọi đơn vị",
        holding: "Đang mượn {count}",
        totalCount: "{count} bạn đọc",
        empty: "Chưa có bạn đọc nào khớp bộ lọc.",
        pagePrev: "Trang trước",
        pageNext: "Trang sau",
        pageOf: "Trang {page}/{pageCount}",
        createTitle: "Đăng ký người đọc mới",
        createLead:
            "Điền thay cho bạn đọc đang đứng trước mặt. Hồ sơ vẫn chờ duyệt để bước xác nhận không bị bỏ qua.",
        createSubmit: "Tạo hồ sơ chờ duyệt",
    },
    registrationQueue: {
        title: "Đăng ký chờ duyệt",
        empty: "Không có đơn đăng ký nào đang chờ.",
        requestedAt: "Gửi lúc {time}",
        dateOfBirth: "Ngày sinh",
        father: "Tên cha",
        mother: "Tên mẹ",
        phone: "Số điện thoại",
        phoneMissing: "Chưa có số — lý do: {reason}",
        parish: "Đơn vị",
        similar: "Gần trùng tên với {name} ({percent}%) — kiểm tra xem có phải đăng ký hai lần.",
        approve: "Duyệt đăng ký",
        reject: "Từ chối",
        rejectReason: "Lý do từ chối",
    },
    readerDetail: {
        title: "Hồ sơ bạn đọc",
        holding: "Đang mượn",
        loanDue: "Hạn {date}",
        loanOverdue: "Quá hạn {days} ngày",
        loanDays: "Còn {days} ngày",
        noLoans: "Không mượn cuốn nào.",
        fields: {
            saintName: "Tên thánh",
            fullName: "Họ và tên",
            dateOfBirth: "Ngày sinh",
            fatherName: "Tên cha",
            motherName: "Tên mẹ",
            phone: "Số điện thoại",
            phoneMissingReason: "Lý do chưa có số điện thoại",
            email: "Email",
            parish: "Đơn vị",
            joinedOn: "Ngày tham gia",
        },
        managerNotes: "Ghi chú của quản lý",
        suspensionReason: "Lý do tạm khoá",
        suspensionReasonLine: "Lý do tạm khoá: {reason}",
        rejectionReason: "Lý do từ chối",
        rejectionReasonLine: "Lý do từ chối: {reason}",
        editProfile: "Sửa hồ sơ",
        editSave: "Lưu thay đổi",
        credentialsTitleNew: "Cấp tài khoản đăng nhập",
        credentialsTitleReset: "Đặt lại mật khẩu",
        credentialsUsername: "Tên đăng nhập",
        credentialsPassword: "Mật khẩu mới",
        credentialsSubmit: "Lưu tài khoản",
        suspend: "Tạm khoá tài khoản",
        suspendNote:
            "Tạm khoá chặn dùng cả tủ sách, không chỉ mượn mới — người đọc vẫn đăng nhập được nhưng không vào được trang nào. Sách đang mượn vẫn giữ nguyên trong hệ thống.",
        suspendReason: "Lý do tạm khoá",
        suspendSubmit: "Tạm khoá",
        reactivate: "Mở khoá lại",
        markLeft: "Đánh dấu đã rời",
    },
    manageAudit: {
        title: "Nhật ký",
        lead: "Mọi thay đổi trong tủ sách, ai làm và lúc nào.",
        when: "lúc {time} ngày {date}",
        groupAll: "Tất cả",
        groups: {
            loans: "Mượn và trả",
            books: "Sách",
            readers: "Bạn đọc",
        },
        actorLabel: "Người thực hiện",
        actorAll: "Mọi người",
        actorEntries: "({count} lượt)",
        fromLabel: "Từ ngày",
        toLabel: "Đến ngày",
        filter: "Lọc",
        empty: "Chưa có hoạt động nào được ghi lại.",
        detail: "Chi tiết",
        rawAction: "Thao tác: {action}",
        fieldHeader: "Trường",
        beforeHeader: "Trước",
        afterHeader: "Sau",
        totalEntries: "{count} lượt ghi",
        prevPage: "Trang trước",
        nextPage: "Trang sau",
    },
    manageExports: {
        heading: "Xuất dữ liệu",
        lead: "Tệp CSV mở được bằng Excel — sao lưu dữ liệu của tủ sách.",
        books: "Tải danh mục sách",
        readers: "Tải danh sách bạn đọc",
        loans: "Tải lịch sử mượn trả",
    },
    manageDashboard: {
        // "Tổng quan", not "Trang chính": copy.manage.dashboard — the nav
        // entry that opens this page — already says "Tổng quan", and a nav
        // word that opens a differently-headed page is two names for one
        // screen. Duplicated as a literal rather than referencing
        // copy.manage.dashboard because `copy` is one object literal and
        // cannot refer to itself mid-definition.
        title: "Tổng quan",
        overdueCard: "Quá hạn",
        registrationsCard: "Chờ duyệt tài khoản",
        requestsCard: "Yêu cầu chờ xử lý",
        viewList: "Xem danh sách",
        lendAction: "Cho mượn",
        lendSub: "Tìm sách · chọn người đọc · xác nhận",
        returnAction: "Nhận trả",
        returnSub: "Tìm sách đang mượn · kiểm tra tình trạng",
        totalsHeading: "Tình hình tủ sách",
        totalTitles: "Đầu sách",
        totalCopies: "Bản sách",
        totalOnLoan: "Đang cho mượn",
        totalReaders: "Bạn đọc",
    },
    /**
     * The manager's borrow-request queue. Its own section rather than a
     * branch of `circulation.requests`: that one is the READER's wording
     * for their own row ("Bạn đang chờ cuốn này"), and these are a
     * volunteer's words about somebody else's.
     */
    manageRequests: {
        title: "Yêu cầu mượn",
        subtitle: "Xếp theo thứ tự đăng ký.",
        subtitleCounted: "{count} cuốn có người đang chờ · Xếp theo thứ tự đăng ký.",
        empty: "Hiện không có bạn đọc nào đang chờ mượn sách.",
        waitingCount: "{count} người đang chờ",
        requestedLine: "Đăng ký {time} ngày {date}",
        holdNote: "Đang giữ chỗ cho bạn này · hết hạn giữ {time} ngày {date}",
        holdNoteBare: "Đang giữ chỗ cho bạn này",
        holdExpiredNote: "Thời gian giữ chỗ đã hết lúc {time} ngày {date}",
        holdExpiredBare: "Thời gian giữ chỗ đã hết",
        copySuffix: "bản {code}",
        firstPendingNote: "Giữ chỗ {days} ngày kể từ khi duyệt.",
        notYourTurnNote: "Chỉ duyệt được khi tới lượt.",
        approveButton: "Duyệt & giữ chỗ",
        copyLabel: "Bản sách",
        noFreeCopies: "Chưa có bản nào rảnh để giữ chỗ.",
        rejectSummary: "Từ chối",
        rejectReasonLabel: "Lý do từ chối",
        // Ruling 2, settled: the reason is optional. The hint says so
        // rather than leaving a volunteer to find out by submitting.
        rejectReasonHint: "Không bắt buộc.",
        rejectConfirm: "Xác nhận từ chối",
        handoverButton: "Xác nhận trao sách",
        nothingAutomatic: "Hệ thống không tự động giữ chỗ. Quản lý quyết định từng trường hợp.",
    },
    circulation: {
        rules: {
            copy_not_available: "Bản sách này đang được mượn hoặc đang giữ chỗ.",
            copy_lost_or_retired: "Bản sách này đã mất hoặc ngừng dùng.",
            membership_not_active: "Tài khoản đang tạm khoá, không thể mượn thêm.",
            loan_limit_reached: "Bạn đọc đã mượn tối đa số sách cho phép.",
            no_renewals_remaining: "Bạn đã dùng hết số lần gia hạn cho lượt mượn này.",
            title_has_queue: "Có bạn khác đang chờ mượn cuốn này, không thể gia hạn.",
            // Settled decision 4. Must stay word-for-word identical to
            // lang/vi/rules.php's title_has_no_copies: the list row reads
            // this one, the confirm screen's `blocking` reads this one,
            // and a server refusal would read the PHP one — three surfaces,
            // one sentence, or the volunteer gets two answers.
            title_has_no_copies: "Cuốn này chưa có bản sách nào trong tủ.",
        },
        steps: ["Tìm sách", "Chọn người đọc", "Xác nhận"],
        lend: {
            title1: "Tìm sách cần cho mượn",
            title2: "Chọn người đọc",
            title3: "Xác nhận cho mượn",
            searchBookPlaceholder: "Tên sách hoặc mã bản",
            searchBookHint: "Không cần gõ dấu — gõ de men vẫn tìm ra Dế Mèn.",
            searchReaderPlaceholder: "Tên bạn đọc",
            search: "Tìm",
            available: "Còn sách",
            copies: "{available}/{total} bản",
            holding: "Đang mượn {count} cuốn",
            registerNewReader: "Đăng ký người đọc mới",
            // Settled decision 3. The lead is what tells a volunteer this
            // form is NOT the readers-list one: no waiting, because the
            // child is standing here with a book.
            newReaderTitle: "Đăng ký người đọc mới",
            newReaderLead:
                "Bạn đọc dùng được ngay, không cần chờ duyệt — điền xong là quay lại bước xác nhận cho mượn.",
            newReaderSubmit: "Lưu và cho mượn tiếp",
            bookLabel: "Sách",
            copyLabel: "Bản",
            readerLabel: "Người đọc",
            lentOnLabel: "Ngày mượn",
            dueOnLabel: "Hạn trả",
            confirmButton: "Xác nhận cho mượn",
            bookMissing: "Chưa chọn sách — quay lại bước 1.",
            readerMissing: "Chưa chọn người đọc — quay lại bước 2.",
        },
        returns: {
            title: "Nhận trả sách",
            lostTitle: "Bạn đọc báo làm mất",
            searchPlaceholder: "Tên sách, tên bạn đọc hoặc mã bản",
            search: "Tìm",
            dueLine: "Hạn trả {date}",
            overdueLine: "Quá hạn {days} ngày",
            conditionLegend: "Tình trạng sách khi trả",
            noteLabel: "Ghi chú",
            confirmButton: "Xác nhận nhận trả",
            reportLostLink: "Bạn đọc báo làm mất",
            backToReturns: "Quay lại nhận trả",
            lostExplain:
                "Sau khi xác nhận, bản {code} sẽ chuyển sang trạng thái Đã mất và lượt mượn khép lại là mất sách.",
            lostNoteLabel: "Ghi chú",
            lostConfirmButton: "Xác nhận báo mất",
            noneFound: "Không tìm thấy lượt mượn nào đang mở.",
            chooseFirst: "Tìm và chọn lượt mượn cần xử lý.",
            waitingLegend: "{count} bạn đọc đang chờ cuốn này",
            noHoldOption: "Không giữ chỗ, trả về kệ",
            holdForOption: "Giữ chỗ cho {name}",
            holdForRequestedSuffix: "đăng ký {time} ngày {date}",
            nothingAutomatic: "Hệ thống không tự động giữ chỗ. Quản lý quyết định từng trường hợp.",
        },
        overdue: {
            title: "Sách quá hạn",
            sortMostLate: "Trễ nhất trước",
            sortLeastLate: "Trễ ít trước",
            sortBorrower: "Theo tên bạn đọc",
            daysLate: "Trễ {days} ngày",
            dueLine: "Hạn trả {date}",
            empty: "Không có sách nào quá hạn. Tuyệt vời!",
            noPhone: "Chưa có số điện thoại",
        },
        voidLoan: {
            button: "Huỷ lượt mượn",
            reasonLabel: "Lý do huỷ",
            confirm: "Huỷ",
        },
        entryPoints: {
            lend: "Cho mượn",
            receive: "Nhận trả",
        },
        myLoans: {
            overviewTitle: "Trang của tôi",
            historyTitle: "Lịch sử mượn sách",
            currentSection: "Sách đang mượn",
            requestsSection: "Đăng ký mượn",
            requestsEmpty: "Bạn chưa đăng ký chờ mượn cuốn nào.",
            requestPositionLine: "Bạn ở vị trí {position}",
            requestHeldLine: "Đã sẵn sàng, nhận trước {time} ngày {date}",
            requestHeldLineNoDate: "Đã sẵn sàng để nhận",
            recentSection: "Vừa trả gần đây",
            daysRemaining: "Còn {days} ngày",
            dueToday: "Đến hạn hôm nay",
            overdueDays: "Quá hạn {days} ngày",
            dueLine: "Hạn trả {date}",
            renewButton: "Xin gia hạn",
            renewedLine: "Đã gia hạn {count} lần",
            returnedLine: "Đã trả ngày {date}",
            lentLine: "Mượn ngày {date}",
            statusReturned: "Đã trả",
            statusActive: "Đang mượn",
            statusLost: "Báo mất",
            statusVoided: "Đã huỷ",
            emptyLoans: "Bạn chưa mượn cuốn nào. Ra tủ sách chọn một cuốn nhé!",
            emptyHistory: "Chưa có lượt mượn nào.",
            prev: "Trước",
            next: "Sau",
        },
        requests: {
            requestButton: "Xin mượn",
            queueButton: "Đăng ký chờ mượn",
            waitingLine: "Bạn đang chờ cuốn này · vị trí {position}",
            heldLine: "Sách đã để dành cho bạn · nhận trước {time} ngày {date}",
            heldLineNoDate: "Sách đã để dành cho bạn",
            cancelButton: "Huỷ yêu cầu",
        },
    },
} as const;

/**
 * Fill a copy template's `{param}` placeholders. A missing param leaves the
 * placeholder text visible (`{count}`) rather than silently rendering
 * "undefined" — a wrong caller shows up as an obviously broken string
 * instead of a plausible one.
 */
export function t(template: string, params: Record<string, string | number>): string {
    return template.replace(/\{(\w+)\}/g, (match, key: string) =>
        key in params ? String(params[key]) : match,
    );
}
