<?php

namespace App\Models;

use App\Models\Concerns\BelongsToBookshelf;
use Database\Factories\BookFactory;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @property string $title_folded generated by the database — never assign
 * @property string $author_folded generated by the database — never assign
 */
class Book extends Model
{
    /** @use HasFactory<BookFactory> */
    use BelongsToBookshelf, HasFactory, HasUuids, SoftDeletes;

    /**
     * The database computes these; a write raises errno 1906. Guarding them
     * keeps Book::create($other->toArray()) and row-replicating seeders
     * from ever including them in an INSERT.
     */
    protected $guarded = ['title_folded', 'author_folded', 'slug_key'];

    public function getRouteKeyName(): string
    {
        return 'slug';   // spec §6: reader and manager URLs both bind by slug
    }

    /** @return array<string, string> */
    protected function casts(): array
    {
        return ['is_published' => 'boolean'];
    }

    /** @return BelongsTo<Category, $this> */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /** @return HasMany<BookCopy, $this> */
    public function copies(): HasMany
    {
        return $this->hasMany(BookCopy::class);
    }
}
